user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: william
    password: william

mysql:
  db: trading_system
  host: 192.168.119.128
  password: william
  port: 3306
  user: root

#url: http://www.tcpjwtester.top
url: http://192.168.119.128