user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: william
    password: william

mysql:
  db: trading_system
  host: 192.168.119.128
  password: william
  port: 3306
  user: root

redis:
  host: 192.168.119.128
  port: 6379
  db: 0

#url: http://www.tcpjwtester.top
url: http://192.168.119.128

jenkins:
  url: http://localhost:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=91c9480370d9e07edcdbfa2aeecae5d1f99625ad35a3e65ff85acbd629550204

qywx_group:
  webhook: todu
